name = "lean_study"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanStudy"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
linter.unusedVariables = false
linter.all = true
linter.checkSorry = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanStudy"
