/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 072e9eb8-6d55-469b-a224-9ce1e85b3f77

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module proves that there are infinitely many prime numbers congruent to 3 modulo 4.
It uses Dirichlet's theorem on arithmetic progressions to show that the set `{p : ℕ | Nat.Prime p ∧ p % 4 = 3}` is infinite.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
There are infinitely many prime numbers p such that p ≡ 3 (mod 4).
-/
theorem infinitely_many_primes_mod_4_eq_3 : Set.Infinite {p : ℕ | Nat.Prime p ∧ p % 4 = 3} := by
  have h : {p : ℕ | p.Prime ∧ (p : ZMod 4) = 3}.Infinite :=
    Nat.infinite_setOf_prime_and_eq_mod (by decide)
  apply h.mono
  rintro p ⟨hp, hpm⟩
  refine ⟨hp, ?_⟩
  have h4 : ((p : ℕ) : ZMod 4) = ((3 : ℕ) : ZMod 4) := by exact_mod_cast hpm
  rw [ZMod.natCast_eq_natCast_iff, Nat.ModEq] at h4
  omega
