import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.Calculus.FDeriv.Linear
import Mathlib.Topology.Algebra.Module.FiniteDimension

noncomputable section
open NormedSpace Matrix
open scoped Matrix Norms.Operator

variable {n : ℕ}

/-- Linear map sending a matrix to the result of multiplying a fixed vector on the right. -/
def mulVecLinear (x₀ : Fin n → ℝ) :
    Matrix (Fin n) (Fin n) ℝ →ₗ[ℝ] (Fin n → ℝ) where
  toFun A := A.mulVec x₀
  map_add' A B := by simp [add_mulVec]
  map_smul' r A := by simp [smul_mulVec]

/-- Continuous linear map counterpart of `mulVecLinear`. -/
def mulVecCLM (x₀ : Fin n → ℝ) :
    Matrix (Fin n) (Fin n) ℝ →L[ℝ] (Fin n → ℝ) :=
  LinearMap.toContinuousLinearMap (mulVecLinear (n := n) x₀)

@[simp]
lemma mulVecCLM_apply (x₀ : Fin n → ℝ) (A : Matrix (Fin n) (Fin n) ℝ) :
    mulVecCLM (n := n) x₀ A = A.mulVec x₀ := rfl

/-- The canonical solution of the linear ODE `x' = A ⋅ x` expressed via the matrix exponential. -/
def linearSystemSolution (A : Matrix (Fin n) (Fin n) ℝ) (x₀ : Fin n → ℝ)
    (t : ℝ) : Fin n → ℝ :=
  (exp ℝ (t • A)).mulVec x₀

/-- The solution satisfies the prescribed initial condition. -/
@[simp]
lemma linearSystemSolution_zero (A : Matrix (Fin n) (Fin n) ℝ) (x₀ : Fin n → ℝ) :
    linearSystemSolution A x₀ 0 = x₀ := by
  classical
  simp [linearSystemSolution, zero_smul]

/-- The solution solves the linear ODE `x' = A ⋅ x`. -/
lemma linearSystemSolution_deriv (A : Matrix (Fin n) (Fin n) ℝ)
    (x₀ : Fin n → ℝ) (t : ℝ) :
    HasDerivAt (linearSystemSolution A x₀)
      (A.mulVec (linearSystemSolution A x₀ t)) t := by
  classical
  -- derivative of the matrix exponential
  have hExp :
      HasDerivAt (fun u : ℝ => exp ℝ (u • A)) (exp ℝ (t • A) * A) t := by
    simpa using
      (hasDerivAt_exp_smul_const (𝕂 := ℝ)
        (𝔸 := Matrix (Fin n) (Fin n) ℝ) (x := A) (t := t))
  have hExpF := hExp.hasFDerivAt
  -- transport through the linear map `mulVec` with fixed vector `x₀`
  have hDeriv :
      HasDerivAt (linearSystemSolution A x₀)
        ((exp ℝ (t • A) * A).mulVec x₀) t := by
    set L := mulVecCLM (n := n) x₀
    have hCompF :=
      (ContinuousLinearMap.hasFDerivAt (x := exp ℝ (t • A)) L).comp t hExpF
    have hComp := hCompF.hasDerivAt
    simpa [L, linearSystemSolution, Function.comp] using hComp
  -- commute to rewrite the derivative in the desired form
  have hCommA : Commute A (t • A) := (Commute.refl A).smul_right (M := ℝ) t
  have hCommExp : Commute A (exp ℝ (t • A)) := hCommA.exp_right ℝ
  have hSwap :
      (exp ℝ (t • A) * A).mulVec x₀ =
        A.mulVec ((exp ℝ (t • A)).mulVec x₀) := by
    have hMat : exp ℝ (t • A) * A = A * exp ℝ (t • A) := hCommExp.symm.eq
    simp [hMat, Matrix.mulVec_mulVec]
  simpa [linearSystemSolution, hSwap] using hDeriv

/-- Existence of solutions for linear ODEs with a regular matrix `A`. -/
theorem linearSystem_solutionExists
    (A : Matrix (Fin n) (Fin n) ℝ) (hA : IsUnit A.det) (x₀ : Fin n → ℝ) :
    ∃ x : ℝ → Fin n → ℝ,
      x 0 = x₀ ∧
      (∀ t, HasDerivAt (fun s => x s) (A.mulVec (x t)) t) ∧
      ∀ t, x t = linearSystemSolution A x₀ t := by
  classical
  have _ := hA -- ensures the regularity assumption is recorded
  refine ⟨linearSystemSolution A x₀, ?_, ?_, ?_⟩
  · simp [linearSystemSolution_zero]
  · intro t
    exact linearSystemSolution_deriv (n := n) A x₀ t
  · intro t; rfl

/-- The matrix exponential has an additive rule along the one-parameter subgroup generated by `A`. -/
lemma matrix_exp_additive (A : Matrix (Fin n) (Fin n) ℝ) (t s : ℝ) :
    exp ℝ ((t + s) • A) = exp ℝ (t • A) * exp ℝ (s • A) := by
  classical
  have hComm : Commute (t • A) (s • A) := by
    have hAA : Commute A A := Commute.refl A
    have h1 : Commute (t • A) A := hAA.smul_left (M := ℝ) t
    have h2 : Commute (t • A) (s • A) := h1.smul_right (M := ℝ) s
    simpa using h2
  have h := Matrix.exp_add_of_commute (𝕂 := ℝ)
      (A := t • A) (B := s • A) hComm
  simpa [add_smul] using h
